apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    role: proxy
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gateway
    role: proxy
    tier: backend
